package fr.uge.android.watchoid.ui

enum class ActiveScreen {
    SERVICE_TESTS_LIST,
    SERVICE_TEST_DETAILS,
    SERVICE_TEST_CREATION,
    SERVICE_TEST_HISTORY_ALL,
    SERVICE_TEST_HISTORY_DETAILS,
    JEU_SEB,
    SPACE_INVADER,
}